<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'Alamsyah Firdaus',
                'email' => 'alamsyah.firdaus.af31@gmail.com',
                'password' => Hash::make('alamsyah.firdaus.af31@gmail.com'),
                'role' => 'kia',
                'mother_type' => null,
                'birth_date' => null,
                'phone' => '089693839624',
                'address' => null,
                'district_id' => 8,
                'occupation' => null,
                'photo' => null,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Siti Nurhaliza',
                'email' => 'ibu1@example.com',
                'password' => Hash::make('password'),
                'role' => 'ibu',
                'mother_type' => 'nifas',
                'birth_date' => '1995-04-10',
                'phone' => '081234567890',
                'address' => 'Tasikmalaya',
                'district_id' => 8,
                'occupation' => 'Ibu Rumah Tangga',
                'photo' => null,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rina Amelia',
                'email' => 'ibu2@example.com',
                'password' => Hash::make('password'),
                'role' => 'ibu',
                'mother_type' => 'hamil',
                'birth_date' => '1990-03-20',
                'phone' => '081234567891',
                'address' => 'Bandung',
                'district_id' => 8,
                'occupation' => 'Guru',
                'photo' => null,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ayu Lestari',
                'email' => 'bidan1@example.com',
                'password' => Hash::make('password'),
                'role' => 'bidan',
                'mother_type' => null,
                'birth_date' => '1988-08-15',
                'phone' => '081234567892',
                'address' => 'Garut',
                'district_id' => 8,
                'occupation' => 'Bidan',
                'photo' => null,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sari Wijaya',
                'email' => 'bidan2@example.com',
                'password' => Hash::make('password'),
                'role' => 'bidan',
                'mother_type' => null,
                'birth_date' => '1985-12-01',
                'phone' => '081234567893',
                'address' => 'Sumedang',
                'district_id' => 8,
                'occupation' => 'Bidan',
                'photo' => null,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dewi Kartika',
                'email' => 'kia1@example.com',
                'password' => Hash::make('password'),
                'role' => 'kia',
                'mother_type' => null,
                'birth_date' => '1980-06-30',
                'phone' => '081234567894',
                'address' => 'Ciamis',
                'district_id' => 8,
                'occupation' => 'Kader KIA',
                'photo' => null,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dinda Rosdiana',
                'email' => 'ibu3@example.com',
                'password' => Hash::make('password'),
                'role' => 'ibu',
                'mother_type' => null,
                'mother_type' => 'hamil',
                'birth_date' => '1993-07-11',
                'phone' => '081234567895',
                'address' => 'Cirebon',
                'district_id' => 8,
                'occupation' => 'Wiraswasta',
                'photo' => null,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Diah Anggraini',
                'email' => 'ibu4@example.com',
                'password' => Hash::make('password'),
                'role' => 'ibu',
                'mother_type' => null,
                'mother_type' => 'nifas',
                'birth_date' => '1996-09-05',
                'phone' => '081234567896',
                'address' => 'Majalengka',
                'district_id' => 8,
                'occupation' => 'Ibu Rumah Tangga',
                'photo' => null,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nia Pratiwi',
                'email' => 'bidan3@example.com',
                'password' => Hash::make('password'),
                'role' => 'bidan',
                'mother_type' => null,
                'birth_date' => '1989-11-25',
                'phone' => '081234567897',
                'address' => 'Bogor',
                'district_id' => 8,
                'occupation' => 'Bidan',
                'photo' => null,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rosi Annisa',
                'email' => 'ibu5@example.com',
                'password' => Hash::make('password'),
                'role' => 'ibu',
                'mother_type' => null,
                'mother_type' => 'nifas',
                'birth_date' => '1994-01-02',
                'phone' => '081234567899',
                'address' => 'Tasikmalaya',
                'district_id' => 8,
                'occupation' => 'Ibu Rumah Tangga',
                'photo' => null,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
